#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: kaniko-workspace
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 8Gi
#---
apiVersion: batch/v1
kind: Job
metadata:
  name: test-build
spec:
  template:
    spec:
      containers:
      - name: test-build
        image: gcr.io/kaniko-project/executor:latest
        args:
          - "--context=git://github.com/brennancheung/ci-cd-demo#refs/heads/checks"
          - "--dockerfile=./kaniko/Dockerfile"
          - "--destination=core.harbor.volgenic.com/ui/build-test:latest"
          - "--build-arg=HELLOMESSAGE=''hello world from args'"
          #- "--no-push"
        volumeMounts:
          - name: docker-config
            mountPath: /kaniko/.docker
      volumes:
        - name: docker-config
          secret:
            secretName: regcred
            items:
              - key: .dockerconfigjson
                path: config.json
      restartPolicy: Never
  backoffLimit: 1
